// Config for all 65+ AI tools — each has a prompt template + input schema
// Categories match /ai showcase page

export type ToolCategory = "students" | "teachers" | "centers" | "content" | "bi" | "voice" | "automation";

export interface AITool {
  id: string;
  category: ToolCategory;
  title: string;
  desc: string;
  icon: string; // emoji
  systemPrompt: string;
  // ordered list of input fields
  inputs: { name: string; label: string; placeholder: string; type?: "text" | "textarea"; example?: string }[];
  // template that combines inputs into the user message
  template: (inputs: Record<string, string>) => string;
  maxTokens?: number;
  temperature?: number;
}

const PERSIAN_STRICT = "\nهمیشه فقط به فارسی روان و طبیعی پاسخ بده.";

export const AI_TOOLS: AITool[] = [
  // ─── STUDENTS ──────────────────────────────────────────────────
  {
    id: "s_tutor",
    category: "students",
    title: "معلم شخصی AI",
    desc: "استاد خصوصی ۲۴ ساعته — هر سوال درسی رو صبورانه توضیح می‌ده",
    icon: "🎓",
    systemPrompt: "تو یک معلم خصوصی صبور و متخصص هستی. مفاهیم رو ساده کن، مثال روزمره بزن، مرحله‌به‌مرحله توضیح بده." + PERSIAN_STRICT,
    inputs: [
      { name: "topic", label: "موضوع یا سوال", placeholder: "مثلا: تفاوت CSS Grid و Flexbox", type: "textarea", example: "قضیه فیثاغورس رو با مثال توضیح بده" },
    ],
    template: (i) => i.topic,
    maxTokens: 1500,
  },
  {
    id: "s_homework",
    category: "students",
    title: "حل تمرین و مسئله",
    desc: "تمرین یا مسئله رو بفرست، پاسخ گام‌به‌گام همراه توضیح دریافت کن",
    icon: "🧮",
    systemPrompt: "تو حل‌کننده تمرین هستی. ابتدا صورت مسئله رو دوباره بازگو کن، بعد پاسخ رو گام‌به‌گام حل کن، در پایان جواب نهایی رو با ✅ نشان بده." + PERSIAN_STRICT,
    inputs: [
      { name: "problem", label: "متن مسئله", placeholder: "مثلا: مساحت مثلثی با ضلع‌های ۳ و ۴ و زاویه ۹۰ درجه چقدره؟", type: "textarea" },
    ],
    template: (i) => `این مسئله رو حل کن:\n${i.problem}`,
    maxTokens: 1500,
  },
  {
    id: "s_quiz",
    category: "students",
    title: "تولید کوییز خودکار",
    desc: "از هر متن یا موضوعی سوال چهارگزینه‌ای و تشریحی بساز",
    icon: "❓",
    systemPrompt: "تو طراح کوییز آموزشی هستی. سوالات با کیفیت، متنوع (سطح آسان، متوسط، سخت) و همراه پاسخ کلید تولید کن." + PERSIAN_STRICT,
    inputs: [
      { name: "topic", label: "موضوع یا متن", placeholder: "مثلا: مفاهیم پایه HTML", type: "textarea" },
      { name: "count", label: "تعداد سوال", placeholder: "5" },
    ],
    template: (i) => `${i.count || 5} سوال چهارگزینه‌ای درباره «${i.topic}» بساز. هر سوال شامل: صورت + ۴ گزینه + گزینه صحیح + توضیح کوتاه پاسخ.`,
    maxTokens: 2000,
  },
  {
    id: "s_flashcard",
    category: "students",
    title: "فلش‌کارت هوشمند",
    desc: "کارت‌های مرور با روش spaced repetition برای حفظ ماندگار",
    icon: "🗂️",
    systemPrompt: "تو طراح فلش‌کارت آموزشی هستی. کارت‌ها باید کوتاه، دقیق و برای حفظ سریع طراحی شن." + PERSIAN_STRICT,
    inputs: [
      { name: "topic", label: "موضوع", placeholder: "مثلا: کلمات پرکاربرد انگلیسی سطح B1", type: "textarea" },
      { name: "count", label: "تعداد کارت", placeholder: "10" },
    ],
    template: (i) => `${i.count || 10} فلش‌کارت درباره «${i.topic}» بساز. هر کارت: 📌 روی کارت: (سوال یا کلمه)، 💡 پشت کارت: (پاسخ یا معنی + یک مثال کوتاه)`,
    maxTokens: 1800,
  },
  {
    id: "s_studyplan",
    category: "students",
    title: "برنامه مطالعه شخصی",
    desc: "بر اساس ساعت آزادت، برنامه مطالعه بهینه بساز",
    icon: "📅",
    systemPrompt: "تو مربی برنامه‌ریزی مطالعه هستی. برنامه واقع‌بینانه، متعادل و همراه استراحت بساز." + PERSIAN_STRICT,
    inputs: [
      { name: "subject", label: "موضوع/دوره", placeholder: "مثلا: ICDL" },
      { name: "hours", label: "ساعات آزاد در هفته", placeholder: "10 ساعت" },
      { name: "goal", label: "هدف و مهلت", placeholder: "مثلا: آماده شدن برای آزمون تا ۱ ماه دیگه" },
    ],
    template: (i) => `برنامه مطالعه هفتگی برای دوره «${i.subject}» بساز. ساعات آزاد: ${i.hours}. هدف: ${i.goal}. برنامه رو به تفکیک روز/ساعت و همراه پیشنهاد استراحت و مرور بنویس.`,
    maxTokens: 1800,
  },
  {
    id: "s_voice_teacher",
    category: "students",
    title: "معلم صوتی (توضیح کامل)",
    desc: "توضیح صوتی حرفه‌ای درباره هر موضوع",
    icon: "🎙️",
    systemPrompt: "تو معلم صوتی هستی. توضیح کامل، روان و مثل حرف زدن رودررو بنویس، طوری که وقتی خونده شه یا صوتی بشه، طبیعی به گوش برسه." + PERSIAN_STRICT,
    inputs: [
      { name: "topic", label: "موضوع", placeholder: "مثلا: نحوه ساخت وب‌سایت با HTML و CSS", type: "textarea" },
    ],
    template: (i) => `درباره «${i.topic}» یه توضیح کامل، روان و صوتی‌سازی‌شدنی بنویس (حدود ۳ دقیقه خوانده شود).`,
    maxTokens: 1500,
  },
  {
    id: "s_exam_predict",
    category: "students",
    title: "پیش‌بینی سوالات آزمون",
    desc: "با تحلیل سرفصل و الگوی آزمون‌های قبلی، محتمل‌ترین سوالات",
    icon: "🎯",
    systemPrompt: "تو تحلیلگر آزمون هستی. سوالات محتمل رو با نمره احتمال (٪) و علت پیش‌بینی بگو." + PERSIAN_STRICT,
    inputs: [
      { name: "subject", label: "موضوع/درس", placeholder: "مثلا: حسابداری میانه" },
      { name: "context", label: "توضیح سرفصل یا سبک آزمون قبلی", placeholder: "بیشتر تشریحی، ۵ سوال، از فصل ۱ تا ۴", type: "textarea" },
    ],
    template: (i) => `برای درس «${i.subject}» با شرایط زیر، ۱۰ سوال با احتمال بالای اومدن در آزمون پیش‌بینی کن (با درصد احتمال و علت):\n${i.context}`,
    maxTokens: 1800,
  },
  {
    id: "s_weakness",
    category: "students",
    title: "تشخیص نقاط ضعف",
    desc: "بر اساس نمرات و توضیح، دقیقاً می‌گه کجا ضعف داری",
    icon: "🔍",
    systemPrompt: "تو مشاور تحصیلی هستی. نقاط ضعف رو تحلیل کن، علت رو حدس بزن و راه‌حل عملی بده." + PERSIAN_STRICT,
    inputs: [
      { name: "grades", label: "نمرات و مباحث", placeholder: "مثلا: ریاضی 12، فیزیک 8، از فصل انرژی افت شدید داشتم", type: "textarea" },
    ],
    template: (i) => `این وضعیت درسی رو تحلیل کن، نقاط ضعف رو شناسایی کن، علت‌های احتمالی رو بگو و برنامه بهبود ۲ هفته‌ای بده:\n${i.grades}`,
    maxTokens: 1500,
  },
  {
    id: "s_coach",
    category: "students",
    title: "مربی روزانه یادگیری",
    desc: "چالش کوتاه روزانه + انگیزه + تمرکز",
    icon: "🏋️",
    systemPrompt: "تو مربی انگیزشی روزانه هستی. تشویق کوتاه، یه چالش قابل انجام امروز، یه نکته انگیزشی." + PERSIAN_STRICT,
    inputs: [
      { name: "field", label: "زمینه یادگیری", placeholder: "مثلا: طراحی گرافیک" },
      { name: "mood", label: "حال و انرژی امروزت", placeholder: "خسته‌ام / پرانرژی‌ام / بی‌حوصله‌ام" },
    ],
    template: (i) => `من در حوزه «${i.field}» یاد می‌گیرم و امروز ${i.mood} هستم. یه پیام مربی‌گری کوتاه بده: چالش امروزم چیه، چرا مهمه، و یه جمله انگیزشی برای شروع.`,
    maxTokens: 800,
  },
  {
    id: "s_motivation",
    category: "students",
    title: "دستیار انگیزشی",
    desc: "وقتی خسته‌ای، پیام‌های انگیزشی متناسب می‌فرسته",
    icon: "🔥",
    systemPrompt: "تو کوچ انگیزشی صمیمی هستی. یه پیام کوتاه، صادقانه، بدون کلیشه. با یه سوال قدرتمند تموم کن." + PERSIAN_STRICT,
    inputs: [
      { name: "situation", label: "چه اتفاقی افتاده؟", placeholder: "مثلا: امتحان بد دادم / انگیزم رو از دست دادم", type: "textarea" },
    ],
    template: (i) => `یه پیام انگیزشی کوتاه (حدود ۱۰۰ کلمه) برای این وضعیت بده:\n${i.situation}`,
    maxTokens: 500,
  },
  {
    id: "s_revision",
    category: "students",
    title: "برنامه‌ریز مرور هوشمند",
    desc: "تایمینگ دقیق مرور مطالب قبل از فراموشی",
    icon: "🔄",
    systemPrompt: "تو کارشناس روش مطالعه هستی. از الگوی spaced repetition استفاده کن." + PERSIAN_STRICT,
    inputs: [
      { name: "topics", label: "مباحث یاد گرفته‌شده", placeholder: "مثلا: فصل ۱ HTML، فصل ۲ CSS، جلسه ۳ JavaScript", type: "textarea" },
      { name: "date", label: "تاریخ شروع مرور (اختیاری)", placeholder: "امروز" },
    ],
    template: (i) => `یه برنامه مرور با روش spaced repetition برای این مباحث بساز. تایمینگ مرور روزانه رو با فاصله ۱، ۳، ۷، ۱۴، ۳۰ روز بگو:\n${i.topics}`,
    maxTokens: 1500,
  },
  {
    id: "s_career",
    category: "students",
    title: "مشاور مسیر شغلی",
    desc: "بر اساس علاقه و مهارت، مسیر شغلی + دوره‌های بعدی",
    icon: "🧭",
    systemPrompt: "تو مشاور شغلی و کاریابی هستی. با توجه به بازار کار ایران، مسیرهای واقع‌بینانه با درآمد پیشنهاد بده." + PERSIAN_STRICT,
    inputs: [
      { name: "interests", label: "علاقه‌ها و مهارت‌های فعلی", placeholder: "مثلا: عاشق طراحی‌ام، فتوشاپ بلدم، ۲۵ ساله‌ام", type: "textarea" },
      { name: "goal", label: "هدف مالی/شغلی", placeholder: "مثلا: می‌خوام تا ۱ سال دیگه فریلنسر بشم" },
    ],
    template: (i) => `با این اطلاعات، ۳ مسیر شغلی مناسب پیشنهاد بده. برای هر مسیر: مهارت‌های لازم، دوره‌های پیشنهادی، درآمد تقریبی، و یه قدم اول عملی:\nعلاقه‌ها: ${i.interests}\nهدف: ${i.goal}`,
    maxTokens: 1800,
  },

  // ─── TEACHERS ──────────────────────────────────────────────────
  {
    id: "t_lesson_plan",
    category: "teachers",
    title: "طرح درس خودکار",
    desc: "طرح درس ۹۰ دقیقه‌ای کامل با اهداف، فعالیت و ارزیابی",
    icon: "📋",
    systemPrompt: "تو متخصص طراحی طرح درس آموزشگاه فنی‌وحرفه‌ای هستی." + PERSIAN_STRICT,
    inputs: [
      { name: "subject", label: "موضوع درس", placeholder: "مثلا: آموزش لایه در فتوشاپ" },
      { name: "level", label: "سطح هنرجویان", placeholder: "مبتدی/متوسط/پیشرفته" },
      { name: "duration", label: "مدت جلسه", placeholder: "90 دقیقه" },
    ],
    template: (i) => `طرح درس کامل برای این جلسه بساز. شامل: هدف کلی، اهداف رفتاری، وسایل مورد نیاز، شروع کلاس (۱۰ دقیقه)، ارائه (۴۰ دقیقه)، تمرین (۳۰ دقیقه)، ارزیابی (۱۰ دقیقه)، تکلیف.\nموضوع: ${i.subject}\nسطح: ${i.level}\nمدت: ${i.duration}`,
    maxTokens: 2000,
  },
  {
    id: "t_question_bank",
    category: "teachers",
    title: "بانک سوالات AI",
    desc: "هزاران سوال متنوع و طبقه‌بندی‌شده",
    icon: "📚",
    systemPrompt: "تو طراح سوالات امتحان با تنوع سطح و نوع هستی." + PERSIAN_STRICT,
    inputs: [
      { name: "subject", label: "درس/موضوع", placeholder: "مثلا: مفاهیم شبکه ICDL" },
      { name: "types", label: "انواع سوال (اختیاری)", placeholder: "چهارگزینه‌ای، تشریحی، جای خالی" },
      { name: "count", label: "تعداد", placeholder: "10" },
    ],
    template: (i) => `${i.count || 10} سوال متنوع درباره «${i.subject}» بساز (انواع: ${i.types || "چهارگزینه‌ای، تشریحی، جای خالی"}). برای هر سوال سطح دشواری و کلید پاسخ رو مشخص کن.`,
    maxTokens: 2500,
  },
  {
    id: "t_exam_paper",
    category: "teachers",
    title: "طراح ورقه امتحان",
    desc: "ورقه امتحان + بارم‌بندی + پاسخ‌نامه در ۳۰ ثانیه",
    icon: "📝",
    systemPrompt: "تو طراح ورقه امتحان استاندارد هستی." + PERSIAN_STRICT,
    inputs: [
      { name: "subject", label: "درس", placeholder: "مثلا: خیاطی مقدماتی" },
      { name: "chapters", label: "فصل‌ها یا سرفصل‌ها", placeholder: "فصل ۱ تا ۴", type: "textarea" },
      { name: "total_score", label: "نمره کل", placeholder: "20" },
      { name: "duration", label: "مدت زمان", placeholder: "90 دقیقه" },
    ],
    template: (i) => `ورقه امتحان از درس «${i.subject}» طراحی کن. سرفصل‌ها: ${i.chapters}. نمره کل: ${i.total_score}. مدت: ${i.duration}. شامل ۸-۱۰ سوال متنوع با بارم‌بندی و پاسخ‌نامه در پایان.`,
    maxTokens: 2500,
  },
  {
    id: "t_grade",
    category: "teachers",
    title: "تصحیح خودکار برگه (متنی)",
    desc: "متن پاسخ هنرجو رو بده، نمره و بازخورد بگیر",
    icon: "✅",
    systemPrompt: "تو معلم تصحیح‌کننده منصف هستی. نمره از ۲۰ بده و نقاط قوت/ضعف رو ذکر کن." + PERSIAN_STRICT,
    inputs: [
      { name: "question", label: "سوال", placeholder: "متن سوال...", type: "textarea" },
      { name: "correct", label: "پاسخ صحیح", placeholder: "پاسخ درست کامل...", type: "textarea" },
      { name: "student", label: "پاسخ هنرجو", placeholder: "پاسخ نوشته‌شده توسط هنرجو...", type: "textarea" },
    ],
    template: (i) => `این پاسخ رو تصحیح کن.\nسوال: ${i.question}\nپاسخ صحیح: ${i.correct}\nپاسخ هنرجو: ${i.student}\nخروجی: نمره از ۲۰، نقاط قوت، نقاط ضعف، بازخورد سازنده در ۲ خط.`,
    maxTokens: 800,
  },
  {
    id: "t_attendance_intel",
    category: "teachers",
    title: "هوش حضور و غیاب",
    desc: "الگوی غیبت هر هنرجو رو تحلیل کن، ریسک ترک‌تحصیل بگیر",
    icon: "📊",
    systemPrompt: "تو تحلیلگر داده آموزشی هستی. الگو رو شناسایی و ریسک رو دسته‌بندی کن (کم/متوسط/بحرانی)." + PERSIAN_STRICT,
    inputs: [
      { name: "records", label: "سابقه حضور", placeholder: "مثلا: علی: ۸ حضور از ۱۰ / زهرا: ۴ حضور از ۱۰ / احمد: ۹/۱۰", type: "textarea" },
    ],
    template: (i) => `این سابقه حضور رو تحلیل کن، برای هر هنرجو ریسک ترک‌تحصیل و پیشنهاد اقدام بده:\n${i.records}`,
    maxTokens: 1500,
  },
  {
    id: "t_quality",
    category: "teachers",
    title: "تحلیل کیفیت دوره",
    desc: "نظرات + نمرات → نقاط قوت و ضعف دوره",
    icon: "⭐",
    systemPrompt: "تو تحلیلگر کیفیت آموزش هستی." + PERSIAN_STRICT,
    inputs: [
      { name: "feedback", label: "نظرات و نمرات هنرجویان", placeholder: "کپی از نظرات...", type: "textarea" },
    ],
    template: (i) => `این بازخوردها رو تحلیل کن. نقاط قوت، نقاط ضعف، امتیاز کلی از ۱۰ و ۳ پیشنهاد بهبود بده:\n${i.feedback}`,
    maxTokens: 1500,
  },
  {
    id: "t_ppt",
    category: "teachers",
    title: "طراح پاورپوینت AI",
    desc: "اسلایدشوی حرفه‌ای — سرفصل هر اسلاید",
    icon: "🖥️",
    systemPrompt: "تو طراح ارائه هستی. هر اسلاید: عنوان + ۳-۵ بولت + پیشنهاد تصویر/آیکون." + PERSIAN_STRICT,
    inputs: [
      { name: "topic", label: "موضوع ارائه", placeholder: "مثلا: مفاهیم پایه اکسل", type: "textarea" },
      { name: "count", label: "تعداد اسلاید", placeholder: "10" },
    ],
    template: (i) => `${i.count || 10} اسلاید برای ارائه «${i.topic}» طراحی کن. هر اسلاید: عنوان جذاب، ۳-۵ نکته کلیدی، پیشنهاد تصویر.`,
    maxTokens: 2000,
  },
  {
    id: "t_video_script",
    category: "teachers",
    title: "تولید متن ویدیو",
    desc: "اسکریپت جذاب برای ویدیوهای آموزشی",
    icon: "🎬",
    systemPrompt: "تو فیلم‌نامه‌نویس آموزشی هستی. متن روان، تصویری، مخاطب‌محور بنویس." + PERSIAN_STRICT,
    inputs: [
      { name: "topic", label: "موضوع ویدیو", placeholder: "مثلا: چطور با فتوشاپ background حذف کنیم؟", type: "textarea" },
      { name: "duration", label: "مدت", placeholder: "3 دقیقه" },
    ],
    template: (i) => `اسکریپت کامل ویدیوی آموزشی ${i.duration} با موضوع «${i.topic}» بنویس. شامل: هوک اول (۱۰ ثانیه)، مقدمه، ۳ گام اصلی، جمع‌بندی، CTA پایانی.`,
    maxTokens: 2000,
  },
  {
    id: "t_voiceover_script",
    category: "teachers",
    title: "متن صداگذاری",
    desc: "متن آماده برای تبدیل به گفتار طبیعی",
    icon: "🔊",
    systemPrompt: "تو نویسنده متن voice-over هستی. جمله‌های کوتاه، بدون علائم پیچیده، مکث‌ها با . بنویس." + PERSIAN_STRICT,
    inputs: [
      { name: "content", label: "محتوا یا خلاصه", placeholder: "چی می‌خوای گفته شه؟", type: "textarea" },
      { name: "tone", label: "لحن", placeholder: "دوستانه / رسمی / انگیزشی" },
    ],
    template: (i) => `این محتوا رو به متن voice-over ${i.tone || "دوستانه"} تبدیل کن، برای پخش صوتی طبیعی:\n${i.content}`,
    maxTokens: 1500,
  },
  {
    id: "t_live_helper",
    category: "teachers",
    title: "دستیار کلاس آنلاین",
    desc: "سوال هنرجو رو خلاصه کن، پاسخ پیشنهادی بده",
    icon: "🙋",
    systemPrompt: "تو دستیار استاد در کلاس زنده هستی. پاسخ کوتاه، دقیق و آماده گفتن." + PERSIAN_STRICT,
    inputs: [
      { name: "question", label: "سوال هنرجو", placeholder: "متن سوال...", type: "textarea" },
      { name: "context", label: "زمینه درس", placeholder: "چی داشتیم درس می‌دادیم؟" },
    ],
    template: (i) => `در کلاس زنده هنرجو این سوال رو پرسیده در حالی که موضوع «${i.context}» بود.\nسوال: ${i.question}\nخلاصه سوال + پاسخ پیشنهادی برای استاد بگو.`,
    maxTokens: 800,
  },
  {
    id: "t_rewrite",
    category: "teachers",
    title: "بازنویسی متن آموزشی",
    desc: "سخت رو ساده، ساده رو تخصصی کن",
    icon: "✍️",
    systemPrompt: "تو بازنویس متن آموزشی هستی. بسته به سبک خواسته، متن رو تبدیل کن." + PERSIAN_STRICT,
    inputs: [
      { name: "text", label: "متن اصلی", placeholder: "متن رو اینجا بذار...", type: "textarea" },
      { name: "style", label: "سبک بازنویسی", placeholder: "ساده‌ترکن / تخصصی‌ترکن / کوتاه‌ترکن / رسمی‌ترکن" },
    ],
    template: (i) => `این متن رو با سبک «${i.style}» بازنویسی کن:\n${i.text}`,
    maxTokens: 1500,
  },
  {
    id: "t_mentor",
    category: "teachers",
    title: "منتور تدریس",
    desc: "بازخورد سازنده درباره روش تدریست",
    icon: "🎯",
    systemPrompt: "تو منتور استاد هستی. بازخورد صادقانه، کاربردی و مثبت بده." + PERSIAN_STRICT,
    inputs: [
      { name: "desc", label: "توصیف جلسه", placeholder: "چی درس دادی؟ چطور واکنش هنرجوها بود؟ چه چالشی داشتی؟", type: "textarea" },
    ],
    template: (i) => `این جلسه تدریس رو تحلیل کن. نقاط قوت، ۳ ایده بهبود، و یک تکنیک جدید برای دفعه بعد بده:\n${i.desc}`,
    maxTokens: 1500,
  },

  // ─── TRAINING CENTERS ─────────────────────────────────────────
  {
    id: "c_dropout",
    category: "centers",
    title: "پیش‌بینی ترک تحصیل",
    desc: "هنرجویان پرریسک رو شناسایی کن",
    icon: "🚪",
    systemPrompt: "تو تحلیلگر ریسک آموزشگاه هستی. عوامل ریسک رو با درصد اهمیت دسته‌بندی کن." + PERSIAN_STRICT,
    inputs: [
      { name: "data", label: "اطلاعات هنرجو", placeholder: "حضور، پرداخت، نمرات، ارتباط...", type: "textarea" },
    ],
    template: (i) => `این هنرجو رو تحلیل کن، ریسک ترک تحصیل (٪) بده، دلایل و اقدام پیشنهادی:\n${i.data}`,
    maxTokens: 1200,
  },
  {
    id: "c_enrollment",
    category: "centers",
    title: "پیش‌بینی ثبت‌نام",
    desc: "بر اساس روند و فصل، ثبت‌نام دوره بعدی",
    icon: "📈",
    systemPrompt: "تو تحلیلگر ثبت‌نام آموزشگاه هستی." + PERSIAN_STRICT,
    inputs: [
      { name: "history", label: "سابقه ثبت‌نام دوره‌های قبل", placeholder: "بهار: 20، تابستان: 35، پاییز: 15، زمستان: 25", type: "textarea" },
      { name: "course", label: "دوره پیش رو", placeholder: "مثلا: فتوشاپ حرفه‌ای، شروع بهمن" },
    ],
    template: (i) => `با این سابقه، ثبت‌نام دوره جدید رو پیش‌بینی کن، ۳ پیشنهاد برای افزایش ثبت‌نام هم بده:\nسابقه: ${i.history}\nدوره جدید: ${i.course}`,
    maxTokens: 1200,
  },
  {
    id: "c_revenue_forecast",
    category: "centers",
    title: "پیش‌بینی درآمد",
    desc: "درآمد ۳ ماه آینده با سناریو",
    icon: "💰",
    systemPrompt: "تو تحلیلگر مالی آموزشگاه هستی. اعداد و سناریوهای واقعی بده." + PERSIAN_STRICT,
    inputs: [
      { name: "data", label: "درآمد ۶ ماه گذشته", placeholder: "فروردین: 50 میلیون، اردیبهشت: 60...", type: "textarea" },
    ],
    template: (i) => `درآمد ۳ ماه آینده رو در ۳ سناریو (بدبینانه/واقع‌بینانه/خوشبینانه) پیش‌بینی کن با دلایل:\n${i.data}`,
    maxTokens: 1500,
  },
  {
    id: "c_marketing",
    category: "centers",
    title: "دستیار بازاریابی",
    desc: "کمپین کامل با متن، تصویر پیشنهادی، مخاطب",
    icon: "📢",
    systemPrompt: "تو استراتژیست بازاریابی دیجیتال هستی." + PERSIAN_STRICT,
    inputs: [
      { name: "goal", label: "هدف کمپین", placeholder: "مثلا: افزایش ثبت‌نام دوره خیاطی ۳۰٪" },
      { name: "budget", label: "بودجه تقریبی", placeholder: "10 میلیون تومان" },
      { name: "channels", label: "کانال‌ها", placeholder: "اینستا، تلگرام، بنر شهر" },
    ],
    template: (i) => `کمپین بازاریابی ۳۰ روزه با این مشخصات طراحی کن:\nهدف: ${i.goal}\nبودجه: ${i.budget}\nکانال‌ها: ${i.channels}\nخروجی: هدف SMART، مخاطب هدف، پیام کلیدی، تقویم محتوایی، KPI ها.`,
    maxTokens: 2000,
  },
  {
    id: "c_satisfaction",
    category: "centers",
    title: "تحلیل رضایت هنرجو",
    desc: "نظرات و پیام‌ها → سطح رضایت",
    icon: "😊",
    systemPrompt: "تو تحلیلگر sentiment هستی. نظرات رو تحلیل کن." + PERSIAN_STRICT,
    inputs: [
      { name: "feedback", label: "نظرات یا پیام‌ها", placeholder: "کپی چند نظر...", type: "textarea" },
    ],
    template: (i) => `این نظرات رو تحلیل کن. امتیاز رضایت کلی (٪)، ۳ نگرانی اصلی، ۳ نکته مثبت، و اقدام پیشنهادی:\n${i.feedback}`,
    maxTokens: 1500,
  },
  {
    id: "c_crm",
    category: "centers",
    title: "CRM هوشمند",
    desc: "لیدها رو خودکار امتیازدهی کن",
    icon: "👥",
    systemPrompt: "تو تحلیلگر CRM هستی. برای هر لید امتیاز از ۱۰۰ بده و اولویت‌بندی کن." + PERSIAN_STRICT,
    inputs: [
      { name: "leads", label: "لیست لیدها با اطلاعات", placeholder: "علی: زنگ زد، دوره ICDL می‌خواست، بودجه معلوم نیست\nزهرا: در واتساپ پیام داد، دوره خیاطی می‌خواد، فوری", type: "textarea" },
    ],
    template: (i) => `این لیدها رو امتیازدهی و اولویت‌بندی کن، برای هر کدوم اقدام بعدی پیشنهاد بده:\n${i.leads}`,
    maxTokens: 1500,
  },
  {
    id: "c_sales_call",
    category: "centers",
    title: "دستیار فروش تلفنی",
    desc: "اسکریپت مکالمه + پاسخ اعتراض + بستن فروش",
    icon: "📞",
    systemPrompt: "تو فروشنده تلفنی حرفه‌ای هستی. اسکریپت گام‌به‌گام همراه پاسخ به اعتراضات رایج." + PERSIAN_STRICT,
    inputs: [
      { name: "course", label: "دوره", placeholder: "مثلا: فتوشاپ حرفه‌ای، ۱۲ جلسه، ۲ میلیون" },
      { name: "concern", label: "نگرانی رایج مشتری", placeholder: "قیمت بالاست / وقت ندارم / آنلاین یاد نمی‌گیرم" },
    ],
    template: (i) => `اسکریپت مکالمه تلفنی برای فروش این دوره بده، همراه پاسخ به اعتراض «${i.concern}»:\nدوره: ${i.course}`,
    maxTokens: 1500,
  },
  {
    id: "c_whatsapp",
    category: "centers",
    title: "اتوماسیون واتساپ",
    desc: "متن‌های واتساپ برای موقعیت‌های مختلف",
    icon: "💬",
    systemPrompt: "تو کپی‌رایتر پیام واتساپ هستی. کوتاه، صمیمی، با ایموجی." + PERSIAN_STRICT,
    inputs: [
      { name: "scenario", label: "موقعیت", placeholder: "خوش‌آمد به لید جدید / پیگیری هنرجو غایب / یادآوری قسط" },
      { name: "extra", label: "جزئیات (اختیاری)", placeholder: "مثلا: قسط شهریه ۱ میلیون از دوره خیاطی" },
    ],
    template: (i) => `۳ نسخه پیام واتساپ برای موقعیت «${i.scenario}» بنویس. جزئیات: ${i.extra || "-"}`,
    maxTokens: 800,
  },
  {
    id: "c_insta",
    category: "centers",
    title: "تولید محتوای اینستاگرام",
    desc: "پست + استوری + ریلز",
    icon: "📸",
    systemPrompt: "تو مدیر اینستاگرام آموزشگاه هستی. پست جذاب با کپشن + هشتگ + CTA." + PERSIAN_STRICT,
    inputs: [
      { name: "topic", label: "موضوع پست", placeholder: "معرفی دوره جدید / گواهی هنرجو / تخفیف ویژه" },
      { name: "format", label: "فرمت", placeholder: "پست تک‌تصویری / کاروسل / ریلز 30 ثانیه‌ای" },
    ],
    template: (i) => `پست ${i.format} برای اینستاگرام آموزشگاه با موضوع «${i.topic}» بساز. شامل: عنوان جذاب، کپشن ۱۵۰ کلمه‌ای، ۱۲ هشتگ، CTA پایانی.`,
    maxTokens: 1500,
  },
  {
    id: "c_campaign",
    category: "centers",
    title: "طراح کمپین AI",
    desc: "کمپین ۳۰ روزه با تقویم و KPI",
    icon: "🚀",
    systemPrompt: "تو استراتژیست کمپین هستی." + PERSIAN_STRICT,
    inputs: [
      { name: "goal", label: "هدف", placeholder: "مثلا: فروش ۵۰ ثبت‌نام" },
      { name: "context", label: "زمینه و بازار", placeholder: "دوره فتوشاپ در شهرستان زبرخان، رقبا ۲ نفرن", type: "textarea" },
    ],
    template: (i) => `کمپین ۳۰ روزه بساز.\nهدف: ${i.goal}\nزمینه: ${i.context}\nخروجی: تقویم هفتگی، ۵ محتوا، ۳ کانال، KPI روزانه.`,
    maxTokens: 2500,
  },
  {
    id: "c_email",
    category: "centers",
    title: "تولید ایمیل حرفه‌ای",
    desc: "ایمیل خبرنامه، پیگیری، تبلیغاتی",
    icon: "✉️",
    systemPrompt: "تو کپی‌رایتر ایمیل مارکتینگ هستی. Subject جذاب + preheader + متن اصلی + CTA." + PERSIAN_STRICT,
    inputs: [
      { name: "type", label: "نوع ایمیل", placeholder: "خبرنامه / تخفیف / پیگیری / خوش‌آمد" },
      { name: "audience", label: "مخاطب", placeholder: "هنرجویان قبلی / لیدهای جدید" },
      { name: "message", label: "پیام کلیدی", placeholder: "چی می‌خوای بگی؟", type: "textarea" },
    ],
    template: (i) => `ایمیل ${i.type} برای ${i.audience} بنویس.\nپیام: ${i.message}\nخروجی: Subject، Preheader، متن اصلی، CTA.`,
    maxTokens: 1500,
  },
  {
    id: "c_sms",
    category: "centers",
    title: "تولید پیامک هوشمند",
    desc: "۱۶۰ کاراکتری با CTA قوی",
    icon: "📱",
    systemPrompt: "تو کپی‌رایتر پیامک تبلیغاتی هستی. ۳ نسخه ۱۶۰ کاراکتری با CTA واضح." + PERSIAN_STRICT,
    inputs: [
      { name: "purpose", label: "هدف پیامک", placeholder: "دعوت به دوره جدید / یادآوری قسط / تخفیف فوری", type: "textarea" },
    ],
    template: (i) => `۳ نسخه پیامک ۱۶۰ کاراکتری با این هدف بساز: ${i.purpose}`,
    maxTokens: 800,
  },

  // ─── CONTENT AI ────────────────────────────────────────────────
  {
    id: "ct_blog",
    category: "content",
    title: "تولید مقاله بلاگ",
    desc: "مقاله SEO شده ۱۵۰۰ کلمه‌ای",
    icon: "📰",
    systemPrompt: "تو نویسنده SEO حرفه‌ای هستی. تیتر H1، سرتیترهای H2/H3، meta description، متن جذاب." + PERSIAN_STRICT,
    inputs: [
      { name: "topic", label: "موضوع", placeholder: "مثلا: چرا آموزش فنی حرفه‌ای بهترین راه ورود به بازار کار است" },
      { name: "keyword", label: "کلمه کلیدی اصلی", placeholder: "آموزش فنی حرفه‌ای" },
    ],
    template: (i) => `مقاله بلاگ ۱۰۰۰ کلمه‌ای درباره «${i.topic}» با کلمه کلیدی «${i.keyword}» بنویس. شامل: تیتر H1، Meta Description، ۴ سرتیتر H2، متن روان، جمع‌بندی، CTA.`,
    maxTokens: 3000,
  },
  {
    id: "ct_landing",
    category: "content",
    title: "لندینگ پیج ساز",
    desc: "متن کامل صفحه فرود با ساختار حرفه‌ای",
    icon: "🌐",
    systemPrompt: "تو طراح صفحه فرود فروش هستی." + PERSIAN_STRICT,
    inputs: [
      { name: "product", label: "محصول یا دوره", placeholder: "دوره ICDL آنلاین با گواهی رسمی" },
      { name: "audience", label: "مخاطب", placeholder: "دانشجویان و جویندگان کار" },
      { name: "usp", label: "مزیت اصلی", placeholder: "قیمت مناسب + گواهی رسمی + پشتیبانی" },
    ],
    template: (i) => `متن کامل لندینگ پیج برای این محصول بنویس:\nمحصول: ${i.product}\nمخاطب: ${i.audience}\nمزیت: ${i.usp}\nشامل: هدلاین، هدلاین فرعی، ۳ مزیت، ۳ تستیمونیال نمونه، FAQ ۵ سوال، CTA پایانی.`,
    maxTokens: 3000,
  },
  {
    id: "ct_seo",
    category: "content",
    title: "نویسنده SEO",
    desc: "کلمات کلیدی + متا + پیشنهاد ساختار",
    icon: "🔍",
    systemPrompt: "تو متخصص SEO هستی." + PERSIAN_STRICT,
    inputs: [
      { name: "topic", label: "موضوع صفحه", placeholder: "دوره حسابداری با نرم‌افزار هلو" },
    ],
    template: (i) => `برای صفحه «${i.topic}» بده:\n- ۱۰ کلمه کلیدی اصلی + long-tail\n- Title Tag\n- Meta Description\n- ساختار H1/H2 پیشنهادی\n- ۳ سوال FAQ`,
    maxTokens: 1500,
  },
  {
    id: "ct_banner",
    category: "content",
    title: "طراح متن بنر تبلیغاتی",
    desc: "هدلاین + سرتیتر + CTA برای بنر",
    icon: "🖼️",
    systemPrompt: "تو کپی‌رایتر بنر گرافیکی هستی. کوتاه، تأثیرگذار." + PERSIAN_STRICT,
    inputs: [
      { name: "purpose", label: "هدف بنر", placeholder: "معرفی دوره جدید / تخفیف / گواهی رسمی" },
      { name: "size", label: "سایز", placeholder: "بنر وب / استوری اینستا / پوستر A4" },
    ],
    template: (i) => `۵ نسخه متن برای بنر ${i.size} با هدف «${i.purpose}» بنویس. هر نسخه: هدلاین + سرتیتر + CTA.`,
    maxTokens: 800,
  },
  {
    id: "ct_poster",
    category: "content",
    title: "طراح پوستر",
    desc: "متن پوستر دوره، همایش، اطلاع‌رسانی",
    icon: "🎨",
    systemPrompt: "تو کپی‌رایتر پوستر آموزشی هستی." + PERSIAN_STRICT,
    inputs: [
      { name: "event", label: "رویداد", placeholder: "دوره فتوشاپ حرفه‌ای — شروع ۱۵ بهمن", type: "textarea" },
    ],
    template: (i) => `متن پوستر جذاب برای این رویداد بنویس. شامل: تیتر بزرگ، تیتر فرعی، ۳ مزیت، اطلاعات تماس، فراخوان:\n${i.event}`,
    maxTokens: 800,
  },
  {
    id: "ct_social_plan",
    category: "content",
    title: "برنامه‌ریز شبکه اجتماعی",
    desc: "تقویم محتوایی ماهانه با ایده",
    icon: "📅",
    systemPrompt: "تو استراتژیست محتوای شبکه اجتماعی هستی." + PERSIAN_STRICT,
    inputs: [
      { name: "brand", label: "برند و نوع کسب‌وکار", placeholder: "آموزشگاه فنی حرفه‌ای زبرخان" },
      { name: "goals", label: "اهداف ماه", placeholder: "آگاهی + جذب هنرجو + برندسازی" },
    ],
    template: (i) => `تقویم محتوایی ۳۰ روزه اینستاگرام برای «${i.brand}» با هدف «${i.goals}» بساز. برای هر روز: نوع محتوا، موضوع، هشتگ پیشنهادی.`,
    maxTokens: 3000,
  },
  {
    id: "ct_reels",
    category: "content",
    title: "اسکریپت‌نویس ریلز",
    desc: "متن ۳۰ ثانیه‌ای ویروسی با هوک قوی",
    icon: "🎥",
    systemPrompt: "تو نویسنده اسکریپت ریلز ویروسی هستی. ثانیه‌به‌ثانیه با action و dialogue." + PERSIAN_STRICT,
    inputs: [
      { name: "topic", label: "موضوع ریلز", placeholder: "معرفی دوره / نکته آموزشی / قبل و بعد" },
    ],
    template: (i) => `اسکریپت ریلز ۳۰ ثانیه‌ای درباره «${i.topic}» بنویس. شامل: هوک اول ۳ ثانیه، ثانیه‌های ۴-۲۵ محتوا، ۵ ثانیه CTA. حرکت دوربین و نریشن رو مشخص کن.`,
    maxTokens: 1500,
  },
  {
    id: "ct_thumbnail",
    category: "content",
    title: "طراح متن Thumbnail",
    desc: "متن بند انگشتی جذاب برای ویدیو با CTR بالا",
    icon: "🖼️",
    systemPrompt: "تو متخصص thumbnail یوتیوب/آپارات هستی. متن‌های ۳-۵ کلمه‌ای که کلیک می‌خورن." + PERSIAN_STRICT,
    inputs: [
      { name: "video_topic", label: "موضوع ویدیو", placeholder: "مثلا: آموزش لایه فتوشاپ در ۱۰ دقیقه" },
    ],
    template: (i) => `۵ متن جذاب برای thumbnail ویدیو با موضوع «${i.video_topic}» پیشنهاد بده + توصیف تصویر پیشنهادی.`,
    maxTokens: 600,
  },
  {
    id: "ct_img_prompt",
    category: "content",
    title: "پرامپت‌ساز تصویر",
    desc: "پرامپت حرفه‌ای برای Midjourney/DALL-E",
    icon: "🎭",
    systemPrompt: "تو متخصص prompt engineering برای مدل‌های تصویری هستی. پرامپت انگلیسی بده." + PERSIAN_STRICT,
    inputs: [
      { name: "concept", label: "مفهوم مورد نظر (فارسی)", placeholder: "مثلا: دانشجویی که با انگیزه در حال یادگیری فتوشاپ", type: "textarea" },
      { name: "style", label: "سبک", placeholder: "cinematic / realistic / anime / minimalist" },
    ],
    template: (i) => `از این مفهوم فارسی، ۳ پرامپت حرفه‌ای انگلیسی برای Midjourney/DALL-E بنویس (با style ${i.style}):\n${i.concept}`,
    maxTokens: 800,
  },
  {
    id: "ct_video_prompt",
    category: "content",
    title: "پرامپت‌ساز ویدیو",
    desc: "پرامپت برای Sora/Runway/Kling",
    icon: "🎞️",
    systemPrompt: "تو متخصص prompt برای مدل‌های ویدیویی هستی." + PERSIAN_STRICT,
    inputs: [
      { name: "scene", label: "توصیف صحنه (فارسی)", placeholder: "کلاس درس با دانشجویان مشتاق در حال کار با لپ‌تاپ", type: "textarea" },
    ],
    template: (i) => `از این صحنه، ۲ پرامپت حرفه‌ای انگلیسی برای Sora/Runway بنویس. شامل: صحنه، حرکت دوربین، نور، مدت زمان:\n${i.scene}`,
    maxTokens: 800,
  },

  // ─── BUSINESS INTELLIGENCE ────────────────────────────────────
  {
    id: "bi_kpi",
    category: "bi",
    title: "داشبورد KPI",
    desc: "شاخص‌های کلیدی آموزشگاه در یک نگاه",
    icon: "📊",
    systemPrompt: "تو تحلیلگر داشبورد KPI هستی. اعداد رو تحلیل کن، متریک اصلی رو استخراج کن." + PERSIAN_STRICT,
    inputs: [
      { name: "data", label: "داده‌ها", placeholder: "درآمد، تعداد هنرجو، رضایت، نرخ تبدیل...", type: "textarea" },
    ],
    template: (i) => `این داده‌ها رو تحلیل کن. ۵ KPI کلیدی، وضعیت هر کدوم (سبز/زرد/قرمز)، و پیشنهاد اقدام:\n${i.data}`,
    maxTokens: 1500,
  },
  {
    id: "bi_finance",
    category: "bi",
    title: "پیش‌بینی مالی",
    desc: "روند درآمد و هزینه ۶ ماه آینده",
    icon: "📈",
    systemPrompt: "تو تحلیلگر مالی هستی." + PERSIAN_STRICT,
    inputs: [
      { name: "data", label: "درآمد و هزینه ماه‌های اخیر", placeholder: "فروردین: 100 درآمد / 60 هزینه، ...", type: "textarea" },
    ],
    template: (i) => `این داده مالی رو تحلیل کن، ۶ ماه آینده رو پیش‌بینی کن، ۳ ریسک و ۳ فرصت مالی معرفی کن:\n${i.data}`,
    maxTokens: 1500,
  },
  {
    id: "bi_revenue",
    category: "bi",
    title: "تحلیل درآمد",
    desc: "کدوم دوره/استاد/فصل بیشترین درآمد داره",
    icon: "💵",
    systemPrompt: "تو تحلیلگر درآمد هستی." + PERSIAN_STRICT,
    inputs: [
      { name: "data", label: "درآمد به تفکیک", placeholder: "دوره ICDL: 50m، دوره خیاطی: 80m، دوره فتوشاپ: 30m...", type: "textarea" },
    ],
    template: (i) => `این درآمد رو تحلیل کن. برنده و بازنده رو مشخص کن، ۳ پیشنهاد برای افزایش درآمد:\n${i.data}`,
    maxTokens: 1500,
  },
  {
    id: "bi_students",
    category: "bi",
    title: "تحلیل هنرجو",
    desc: "کوهورت، LTV، رفتار خرید",
    icon: "👥",
    systemPrompt: "تو تحلیلگر رفتار مشتری هستی." + PERSIAN_STRICT,
    inputs: [
      { name: "data", label: "داده هنرجویان", placeholder: "میانگین سن، جنسیت، دوره‌های خریداری‌شده، نرخ تکرار خرید", type: "textarea" },
    ],
    template: (i) => `این داده هنرجو رو تحلیل کن. LTV تخمینی، کوهورت اصلی، رفتار خرید، پیشنهاد بازاریابی هدفمند:\n${i.data}`,
    maxTokens: 1500,
  },
  {
    id: "bi_teacher_perf",
    category: "bi",
    title: "عملکرد اساتید",
    desc: "رتبه‌بندی اساتید بر اساس رضایت و نتیجه",
    icon: "🏆",
    systemPrompt: "تو تحلیلگر منابع انسانی آموزشی هستی." + PERSIAN_STRICT,
    inputs: [
      { name: "data", label: "اطلاعات اساتید", placeholder: "علی: میانگین رضایت 4.8، نرخ قبولی 90٪\nزهرا: 4.2، 75٪", type: "textarea" },
    ],
    template: (i) => `اساتید رو رتبه‌بندی کن، نقاط قوت/ضعف هر کدوم، ۲ پیشنهاد آموزشی برای بهبود:\n${i.data}`,
    maxTokens: 1500,
  },
  {
    id: "bi_competitor",
    category: "bi",
    title: "تحلیل رقبا",
    desc: "جایگاه رقابتی خودت رو ببین",
    icon: "🥊",
    systemPrompt: "تو تحلیلگر رقابتی هستی." + PERSIAN_STRICT,
    inputs: [
      { name: "us", label: "ویژگی‌های آموزشگاه ما", placeholder: "قیمت، دوره‌ها، مزایا، ضعف‌ها", type: "textarea" },
      { name: "competitors", label: "رقبا و ویژگی‌هاشون", placeholder: "آموزشگاه A: قیمت پایین، آموزشگاه B: کیفیت بالا", type: "textarea" },
    ],
    template: (i) => `تحلیل رقابتی SWOT انجام بده:\nما: ${i.us}\nرقبا: ${i.competitors}\nخروجی: جدول مقایسه، مزیت رقابتی ما، ۳ استراتژی متمایز.`,
    maxTokens: 2000,
  },
  {
    id: "bi_report",
    category: "bi",
    title: "گزارش هوشمند",
    desc: "گزارش هفتگی/ماهانه با insight",
    icon: "📄",
    systemPrompt: "تو نویسنده گزارش مدیریتی هستی. مختصر، عددی، با تصمیم پیشنهادی." + PERSIAN_STRICT,
    inputs: [
      { name: "period", label: "دوره گزارش", placeholder: "هفته اول بهمن ۱۴۰۴" },
      { name: "data", label: "داده‌های خام", placeholder: "درآمد، ثبت‌نام، مسائل...", type: "textarea" },
    ],
    template: (i) => `گزارش مدیریتی ${i.period} بنویس شامل: خلاصه اجرایی، ۳ متریک کلیدی، ۲ برد بزرگ، ۲ چالش، ۳ پیشنهاد برای دوره بعد:\n${i.data}`,
    maxTokens: 2000,
  },

  // ─── VOICE AI ──────────────────────────────────────────────────
  {
    id: "v_chat_transcript",
    category: "voice",
    title: "چت صوتی (متن)",
    desc: "پاسخ به صورت متن آماده برای TTS",
    icon: "🎧",
    systemPrompt: "تو دستیار صوتی هستی. پاسخ کوتاه، محاوره‌ای، آماده گفتن." + PERSIAN_STRICT,
    inputs: [
      { name: "question", label: "سوال", placeholder: "سوال...", type: "textarea" },
    ],
    template: (i) => `این سوال رو مثل مکالمه دوستانه، کوتاه و آماده پخش صوتی جواب بده:\n${i.question}`,
    maxTokens: 800,
  },
  {
    id: "v_transcribe_process",
    category: "voice",
    title: "پردازش متن پیاده‌شده",
    desc: "متن پیاده‌شده از صوت رو تمیز و اصلاح کن",
    icon: "📝",
    systemPrompt: "تو ادیتور متن پیاده‌شده هستی. اصلاح غلط، جمله‌بندی، اضافه کردن نشانه‌گذاری." + PERSIAN_STRICT,
    inputs: [
      { name: "text", label: "متن خام", placeholder: "متن پیاده‌شده...", type: "textarea" },
    ],
    template: (i) => `این متن پیاده‌شده از صوت رو تمیز کن، غلط املایی/نگارشی رو اصلاح، جمله‌ها رو کامل کن:\n${i.text}`,
    maxTokens: 2000,
  },
  {
    id: "v_tts_prep",
    category: "voice",
    title: "آماده‌سازی TTS",
    desc: "متن رو برای صداگذاری بهینه کن",
    icon: "🎙️",
    systemPrompt: "تو متخصص preparation متن TTS هستی. جمله‌های کوتاه، بدون علائم پیچیده." + PERSIAN_STRICT,
    inputs: [
      { name: "text", label: "متن اصلی", placeholder: "متن...", type: "textarea" },
    ],
    template: (i) => `این متن رو برای پخش صوتی حرفه‌ای بهینه کن. جمله‌ها کوتاه، مکث‌ها با . یا ، ، بدون علائم پیچیده:\n${i.text}`,
    maxTokens: 1500,
  },
  {
    id: "v_translator",
    category: "voice",
    title: "مترجم زنده",
    desc: "ترجمه بین فارسی و انگلیسی",
    icon: "🌍",
    systemPrompt: "تو مترجم زبان هستی. ترجمه روان و طبیعی." + PERSIAN_STRICT,
    inputs: [
      { name: "text", label: "متن مبدأ", placeholder: "متن...", type: "textarea" },
      { name: "to", label: "به زبان", placeholder: "انگلیسی / فارسی / عربی / ترکی" },
    ],
    template: (i) => `این متن رو به ${i.to} ترجمه کن، به‌صورت روان و بومی:\n${i.text}`,
    maxTokens: 1500,
  },
  {
    id: "v_voice_command",
    category: "voice",
    title: "فرمان‌های صوتی",
    desc: "توضیح دستور صوتی → اجرای عملی",
    icon: "🗣️",
    systemPrompt: "تو مترجم فرمان صوتی به عمل هستی." + PERSIAN_STRICT,
    inputs: [
      { name: "command", label: "فرمان صوتی", placeholder: "مثلا: دوره فتوشاپ رو باز کن / نمرات آخر ماه رو نشون بده", type: "textarea" },
    ],
    template: (i) => `این فرمان صوتی رو تحلیل کن، بگو چه اقدامی باید انجام بشه، کدوم صفحه/API و با چه پارامترها:\n${i.command}`,
    maxTokens: 800,
  },

  // ─── AUTOMATION ────────────────────────────────────────────────
  {
    id: "a_workflow",
    category: "automation",
    title: "طراح فرآیند",
    desc: "فرآیند پیچیده رو گام به گام تشریح می‌کنه",
    icon: "⚙️",
    systemPrompt: "تو مهندس فرآیند هستی. workflow قابل drag & drop بنویس." + PERSIAN_STRICT,
    inputs: [
      { name: "process", label: "توصیف فرآیند", placeholder: "مثلا: از ثبت‌نام هنرجو تا صدور گواهی", type: "textarea" },
    ],
    template: (i) => `فرآیند «${i.process}» رو گام‌به‌گام طراحی کن. برای هر گام: عنوان، اقدام، مسئول، ورودی، خروجی، ابزار.`,
    maxTokens: 2000,
  },
  {
    id: "a_cert_text",
    category: "automation",
    title: "متن گواهی",
    desc: "متن رسمی گواهی پایان دوره",
    icon: "🏅",
    systemPrompt: "تو نویسنده متن رسمی گواهی هستی. لحن رسمی و حرفه‌ای." + PERSIAN_STRICT,
    inputs: [
      { name: "name", label: "نام هنرجو", placeholder: "علی احمدی" },
      { name: "course", label: "نام دوره + مدت", placeholder: "فتوشاپ حرفه‌ای، ۶۰ ساعت" },
      { name: "org", label: "نام آموزشگاه", placeholder: "آموزشگاه فنی حرفه‌ای زبرخان" },
    ],
    template: (i) => `متن رسمی گواهی پایان دوره برای این هنرجو بنویس:\nنام: ${i.name}\nدوره: ${i.course}\nآموزشگاه: ${i.org}`,
    maxTokens: 600,
  },
  {
    id: "a_notification",
    category: "automation",
    title: "اعلان هوشمند",
    desc: "پیام درست، به فرد درست، در زمان درست",
    icon: "🔔",
    systemPrompt: "تو طراح اعلان هوشمند هستی. متن کوتاه، شخصی‌سازی‌شده، بدون spam." + PERSIAN_STRICT,
    inputs: [
      { name: "event", label: "رویداد", placeholder: "شروع کلاس ۱ ساعت دیگه / پرداخت قسط / پایان دوره" },
      { name: "audience", label: "مخاطب", placeholder: "هنرجویان دوره فتوشاپ" },
    ],
    template: (i) => `متن اعلان برای رویداد «${i.event}» به «${i.audience}» بنویس. ۲ نسخه: پیامک کوتاه + notification موبایل.`,
    maxTokens: 600,
  },
  {
    id: "a_scheduler",
    category: "automation",
    title: "زمان‌بند AI",
    desc: "زمان‌بندی کلاس‌ها و جلسات",
    icon: "🕐",
    systemPrompt: "تو زمان‌بند هوشمند هستی." + PERSIAN_STRICT,
    inputs: [
      { name: "constraints", label: "محدودیت‌ها", placeholder: "۳ استاد، ۲ اتاق، ۵ دوره، ساعات فعالیت ۹ تا ۲۰", type: "textarea" },
    ],
    template: (i) => `با این محدودیت‌ها، برنامه زمان‌بندی هفتگی بهینه بساز:\n${i.constraints}`,
    maxTokens: 2000,
  },
  {
    id: "a_followup",
    category: "automation",
    title: "پیگیری خودکار",
    desc: "لیدهای بلاتکلیف رو خودکار پیگیری کن",
    icon: "↩️",
    systemPrompt: "تو مدیر پیگیری فروش هستی." + PERSIAN_STRICT,
    inputs: [
      { name: "lead", label: "توصیف لید", placeholder: "علی: ۱ هفته پیش زنگ زد، دوره خواست، هنوز ثبت‌نام نکرده", type: "textarea" },
    ],
    template: (i) => `برای این لید، ۳ متن پیگیری بنویس (پیامک، واتساپ، تماس): متن هر کدوم + زمان مناسب ارسال:\n${i.lead}`,
    maxTokens: 1000,
  },
  {
    id: "a_reminder",
    category: "automation",
    title: "یادآوری هوشمند",
    desc: "یادآوری قسط، جلسه، آزمون",
    icon: "⏰",
    systemPrompt: "تو نویسنده یادآوری صمیمی هستی. کوتاه، مؤدبانه، بدون فشار." + PERSIAN_STRICT,
    inputs: [
      { name: "what", label: "چی رو یادآوری کنیم", placeholder: "قسط شهریه / جلسه فردا / آزمون ۱۰ صبح" },
      { name: "detail", label: "جزئیات", placeholder: "مبلغ / زمان / مکان" },
    ],
    template: (i) => `۲ متن یادآوری صمیمی برای «${i.what}» بنویس. جزئیات: ${i.detail}`,
    maxTokens: 500,
  },
  {
    id: "a_crm_flow",
    category: "automation",
    title: "اتوماسیون CRM",
    desc: "تبدیل لید به مشتری با فرآیند شخصی",
    icon: "🎯",
    systemPrompt: "تو استراتژیست فرآیند CRM هستی." + PERSIAN_STRICT,
    inputs: [
      { name: "lead_source", label: "منبع لید", placeholder: "اینستا / معرفی / تبلیغ گوگل" },
      { name: "product", label: "محصول هدف", placeholder: "دوره فتوشاپ" },
    ],
    template: (i) => `فرآیند اتوماسیون CRM برای تبدیل لید ${i.lead_source} به مشتری «${i.product}» طراحی کن. مراحل: تماس اول (چه زمانی؟)، محتوای پیام، فاصله بین پیگیری‌ها، بستن فروش.`,
    maxTokens: 2000,
  },
];

// helpers
export function getToolById(id: string) {
  return AI_TOOLS.find((t) => t.id === id) || null;
}

export function getToolsByCategory(category: ToolCategory) {
  return AI_TOOLS.filter((t) => t.category === category);
}

export const CATEGORY_META: Record<
  ToolCategory,
  { label: string; gradient: string; accent: string; icon: string }
> = {
  students: {
    label: "هنرجویان",
    gradient: "from-blue-500 via-indigo-500 to-purple-600",
    accent: "text-blue-300",
    icon: "🎓",
  },
  teachers: {
    label: "اساتید",
    gradient: "from-emerald-500 via-teal-500 to-cyan-600",
    accent: "text-emerald-300",
    icon: "👨‍🏫",
  },
  centers: {
    label: "آموزشگاه‌ها",
    gradient: "from-amber-500 via-orange-500 to-red-500",
    accent: "text-amber-300",
    icon: "🏢",
  },
  content: {
    label: "محتوا و بازاریابی",
    gradient: "from-fuchsia-500 via-pink-500 to-rose-500",
    accent: "text-fuchsia-300",
    icon: "🎨",
  },
  bi: {
    label: "هوش تجاری",
    gradient: "from-cyan-500 via-blue-500 to-indigo-600",
    accent: "text-cyan-300",
    icon: "📊",
  },
  voice: {
    label: "هوش صوتی",
    gradient: "from-violet-500 via-purple-500 to-fuchsia-600",
    accent: "text-violet-300",
    icon: "🎙️",
  },
  automation: {
    label: "اتوماسیون",
    gradient: "from-slate-400 via-slate-500 to-slate-700",
    accent: "text-slate-300",
    icon: "⚙️",
  },
};
