"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Award, CheckCircle2, Loader2, Plus, Send, ShieldCheck, Users2 } from "lucide-react";

export default function RankingAdminPanel(){
 const [data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[msg,setMsg]=useState("");
 const [expert,setExpert]=useState({name:"",phone:"",password:""});
 const [assignment,setAssignment]=useState({academyId:"",expertId:"",year:""});
 const load=()=>fetch("/api/ranking/admin").then(r=>r.json()).then(setData).finally(()=>setLoading(false)); useEffect(()=>{ void load(); },[]);
 const act=async(body:any)=>{setMsg("");const r=await fetch("/api/ranking/admin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok){setMsg(`❌ ${d.error}`);return false}setMsg("✅ ذخیره شد");load();return true};
 if(loading)return <div className="flex justify-center py-20"><Loader2 className="h-8 w-8 animate-spin text-cyan-300"/></div>;
 return <div className="space-y-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="flex items-center gap-2 text-2xl font-black"><Award className="h-6 w-6 text-amber-300"/> مدیریت مرکزی رتبه‌بندی</h2><p className="text-xs text-slate-400">کارشناسان، تخصیص پرونده، تایید انتشار و اعتبارسنجی عمومی</p></div><Link href="/expert" className="rounded-xl bg-primary-600 px-4 py-3 text-xs font-black">ورود به داشبورد کارشناسان</Link></div>{msg&&<div className="rounded-xl bg-white/5 p-3 text-xs">{msg}</div>}
 <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[["کل پرونده",data?.stats?.total,ShieldCheck],["منتظر بررسی",data?.stats?.waiting,Users2],["تایید کارشناس",data?.stats?.approved,CheckCircle2],["منتشرشده",data?.stats?.published,Award]].map(([l,v,I]:any)=><div key={l} className="rounded-[16px] border border-white/10 bg-[#111a2e] p-4"><I className="mb-3 h-5 w-5 text-cyan-300"/><div className="text-2xl font-black">{Number(v||0).toLocaleString("fa-IR")}</div><div className="text-[10px] text-slate-400">{l}</div></div>)}</div>
 <div className="grid gap-4 lg:grid-cols-2"><form onSubmit={async e=>{e.preventDefault();if(await act({action:"createExpert",...expert}))setExpert({name:"",phone:"",password:""})}} className="rounded-[18px] border border-white/10 bg-[#111a2e] p-5"><h3 className="mb-4 font-black">ایجاد حساب کارشناس</h3><div className="space-y-2"><input value={expert.name} onChange={e=>setExpert({...expert,name:e.target.value})} placeholder="نام کارشناس" className="w-full rounded-lg bg-white/90 px-3 py-2.5 text-sm text-slate-900"/><input value={expert.phone} onChange={e=>setExpert({...expert,phone:e.target.value})} placeholder="شماره موبایل" dir="ltr" className="w-full rounded-lg bg-white/90 px-3 py-2.5 text-sm text-slate-900"/><input value={expert.password} onChange={e=>setExpert({...expert,password:e.target.value})} placeholder="رمز حداقل ۶ کاراکتر" dir="ltr" className="w-full rounded-lg bg-white/90 px-3 py-2.5 text-sm text-slate-900"/><button className="flex w-full items-center justify-center gap-2 rounded-lg bg-emerald-500 py-3 text-xs font-black text-slate-950"><Plus className="h-4 w-4"/>ساخت حساب کارشناس</button></div></form>
 <form onSubmit={async e=>{e.preventDefault();if(await act({action:"assign",...assignment,year:Number(assignment.year||data.currentYear)}))setAssignment({academyId:"",expertId:"",year:""})}} className="rounded-[18px] border border-white/10 bg-[#111a2e] p-5"><h3 className="mb-4 font-black">تخصیص آموزشگاه به کارشناس</h3><div className="space-y-2"><select value={assignment.academyId} onChange={e=>setAssignment({...assignment,academyId:e.target.value})} className="w-full rounded-lg bg-white/90 px-3 py-2.5 text-sm text-slate-900"><option value="">انتخاب آموزشگاه</option>{data?.institutes?.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={assignment.expertId} onChange={e=>setAssignment({...assignment,expertId:e.target.value})} className="w-full rounded-lg bg-white/90 px-3 py-2.5 text-sm text-slate-900"><option value="">انتخاب کارشناس</option>{data?.experts?.map((x:any)=><option key={x.id} value={x.id}>{x.name} — {x.phone}</option>)}</select><input type="number" value={assignment.year} onChange={e=>setAssignment({...assignment,year:e.target.value})} placeholder={`سال رتبه‌بندی (${data?.currentYear})`} className="w-full rounded-lg bg-white/90 px-3 py-2.5 text-sm text-slate-900"/><button className="flex w-full items-center justify-center gap-2 rounded-lg bg-primary-600 py-3 text-xs font-black"><Send className="h-4 w-4"/>ثبت تخصیص</button></div></form></div>
 <div className="overflow-x-auto rounded-[18px] border border-white/10 bg-[#111a2e]"><table className="w-full min-w-[760px] text-xs"><thead><tr className="border-b border-white/10 text-right text-[10px] text-slate-500"><th className="p-4">آموزشگاه</th><th>سال</th><th>کارشناس</th><th>امتیاز</th><th>رتبه</th><th>وضعیت</th><th>انتشار</th></tr></thead><tbody>{data?.rankings?.map((r:any)=><tr key={r.id} className="border-b border-white/5"><td className="p-4 font-black">{r.academy_name}</td><td>{r.year}</td><td>{r.expert_name||"تخصیص‌نیافته"}</td><td>{Number(r.score||0)}</td><td className="font-black text-amber-300">{r.rank||"—"}</td><td>{r.status}</td><td>{["approved","published"].includes(r.status)?<button onClick={()=>act({action:r.status==="published"?"unpublish":"publish",rankingId:r.id})} className={`rounded-lg px-3 py-2 font-black ${r.status==="published"?"bg-amber-500/20 text-amber-300":"bg-emerald-500 text-slate-950"}`}>{r.status==="published"?"لغو انتشار":"انتشار و استعلام"}</button>:<span className="text-slate-600">پس از تایید کارشناس</span>}</td></tr>)}</tbody></table></div>
 </div>
}
