"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { CheckCircle2, Loader2, ShieldCheck } from "lucide-react";

export default function ExpertSetupPage(){
 const [state,setState]=useState<any>(null),[form,setForm]=useState({name:"",phone:"",password:""}),[loading,setLoading]=useState(false),[msg,setMsg]=useState("");
 useEffect(()=>{fetch("/api/ranking/bootstrap").then(async r=>({ok:r.ok,data:await r.json()})).then(x=>setState(x)).catch(()=>setState({ok:false,data:{error:"خطا در اتصال"}}))},[]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setLoading(true);const r=await fetch("/api/ranking/bootstrap",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();setLoading(false);if(!r.ok)return setMsg(`❌ ${d.error}`);setMsg("✅ حساب مستقل کارشناس ساخته شد. اکنون با همین حساب وارد شوید.");setState({ok:true,data:{canSetup:false}})};
 return <main className="min-h-screen bg-[#071426] px-4 py-16 text-white"><div className="mx-auto max-w-md rounded-[24px] border border-cyan-400/20 bg-[#0b2946] p-6 shadow-2xl"><div className="text-center"><ShieldCheck className="mx-auto h-12 w-12 text-cyan-300"/><h1 className="mt-3 text-xl font-black">راه‌اندازی اولیه حساب کارشناس</h1><p className="mt-2 text-[11px] leading-6 text-slate-400">این صفحه فقط یک‌بار برای ساخت اولین حساب مستقل کارشناس فعال است. پس از آن مدیر کل هیچ دسترسی عملیاتی به رتبه‌بندی نخواهد داشت.</p></div>{!state?<Loader2 className="mx-auto mt-8 h-7 w-7 animate-spin"/>:!state.ok?<div className="mt-6 rounded-xl bg-red-500/10 p-3 text-xs text-red-300">{state.data.error}<div className="mt-3"><Link href="/login?callbackUrl=/expert/setup" className="text-cyan-200">ورود مالک سامانه</Link></div></div>:state.data.canSetup?<form onSubmit={submit} className="mt-6 space-y-3"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="نام و نام خانوادگی کارشناس" className="w-full rounded-xl bg-white/95 px-3 py-3 text-sm text-slate-900"/><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="شماره موبایل کارشناس" dir="ltr" className="w-full rounded-xl bg-white/95 px-3 py-3 text-sm text-slate-900"/><input value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="رمز عبور حداقل ۶ کاراکتر" dir="ltr" className="w-full rounded-xl bg-white/95 px-3 py-3 text-sm text-slate-900"/><button disabled={loading} className="flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-500 py-3 font-black text-slate-950">{loading?<Loader2 className="h-4 w-4 animate-spin"/>:<CheckCircle2 className="h-4 w-4"/>}ساخت حساب مستقل کارشناس</button></form>:<div className="mt-6 rounded-xl bg-emerald-500/10 p-4 text-center text-xs text-emerald-200"><CheckCircle2 className="mx-auto mb-2 h-6 w-6"/>راه‌اندازی اولیه انجام شده است.<br/><Link href="/login?callbackUrl=/expert" className="mt-3 inline-block rounded-lg bg-white px-4 py-2 font-black text-slate-900">ورود کارشناس</Link></div>}{msg&&<div className="mt-4 rounded-xl bg-white/5 p-3 text-xs">{msg}</div>}</div></main>
}
